on:
  push:
    branches:
      - rc*

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: check for proper rc tag
        run: |
          if [[ "${GITHUB_REF#refs/heads/}" =~ ^(rc[0-9]+(\.[0-9]+)*)$ ]]; then
            echo "Valid branch format!"
          else
            echo "Invalid branch format for rc branch!"
            exit 1
          fi
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: simple
          skip-github-release: true
          target-branch: ${{ github.ref_name }}

